docs: Refactored files and added installation guide
moja-global/FLINT-UI pull request #16
Opened 2021-07-24 18:10 UTC by iamrajiv

2021-07-24 22:20 UTC, aornugent requested changes

2021-07-24 22:20 UTC, aornugent commented on README.md
> +UI for FLINT.Cloud project which aims to build a continuous deployment pipeline to offer FLINT as a SaaS overcloud
Please change to a "A FLINT client, written in Vue, to provide an awesome user interface for configuring simulations using the FLINT.Cloud APIs."

2021-07-24 22:20 UTC, aornugent commented on README.md
> +This project is UI and dashboard for [FLINT.Cloud](https://github.com/moja-global/FLINT.Cloud) project which aims to build a continuous deployment pipeline to offer FLINT as a SaaS overcloud. The pro
Change to "This project provides an intuitive way for new to explore some preconfigured FLINT modules, including the Generic Budget Carbon Model (GCBM), in order to better understand how the FLINT system works. Our client is written as a Web application and can be used in a local or remote environment. Please contact us if you'd like help deploying your own cloud instance or customising the client."

2021-07-24 22:20 UTC, aornugent commented on README.md
> +1. Clone [FLINT.UI](https://github.com/moja-global/FLINT-UI) repository and get inside the repository directory. Now you have to build a `docker-compose.yml` file so follow the below command:
I think this needs to include the git commands:

```
git clone --recursive... 
```

2021-07-24 22:20 UTC, aornugent commented on README.md
> +Now you can run any all the containers by clicking on the `RUN` button. You can use the command line too to run these images. All containers list will look like this in the Docker app:
The containers should already be running after `docker-compose up` you can test this by dropping the `-d`

2021-07-24 22:20 UTC, aornugent commented on README.md
> +1. Now you can run the Vue app to get the dashboard. Go to the `flint.ui` folder of [FLINT.UI](https://github.com/moja-global/FLINT-UI) repository and run the below command:
This should already be running in the container, but might still be helpful to build the Vue app locally if it's faster? We still haven't quite cracked hot reloading within the container.

2021-07-24 22:22 UTC, aornugent commented on README.md
> +1. Clone [FLINT.UI](https://github.com/moja-global/FLINT-UI) repository and get inside the repository directory. Now you have to build a `docker-compose.yml` file so follow the below command:
https://github.com/moja-global/FLINT-UI/pull/1#issuecomment-880523212

2021-07-26 11:29 UTC, aornugent approved these changes

2021-07-26 11:29 UTC, aornugent commented on README.md
> +
Can you please the instruction: "To view the UI please navigate to localhost:{{default port in docker-compose.yml}}" <- but with the correct default port?

2021-07-26 11:29 UTC, aornugent commented on README.md
> +Now you have to get inside the repository directory and to build the `docker-compose.yml` file follow the below command:
Add these instructions in the next step in your list (i.e. item 3.)

2021-07-26 11:29 UTC, aornugent commented on README.md
> +
A screenshot of the UI would be great too!

2021-07-26 11:29 UTC, aornugent commented on README.md
> +Now you can run any all the containers by clicking on the `RUN` button. You can use the command line too to run these images. All containers list will look like this in the Docker app:
I'd put this example at the end and also show people how to shut down the containers, either using the Docker app or with `ctrl-c` in the terminal running the containers, **or** running `docker-compose down`.

2021-07-26 11:29 UTC, aornugent commented on README.md
> +docker-compose up
Can you please explain how to run docker compose in detached mode with `-d`

2021-07-26 11:30 UTC, aornugent commented
Nice one @iamrajiv - happy for you to merge after these changes.

@shubhamkarande13 @waridrox - last chance to review.

2021-07-26 13:26 UTC, shubhamkarande13 approved these changes

2021-07-26 16:29 UTC, merged