feat: datepicker point component created in ant design
moja-global/FLINT-UI pull request #222
Opened 2022-04-03 22:22 UTC by joharikushagra

# Pull Request Template

## Description

feat #177. DatepickerPointAnt component created styled with ant-design.

## Additional Context (Please include any Screenshots/gifs if relevant)
![Screenshot 2022-04-04 031157](https://user-images.githubusercontent.com/57484457/161451233-a2ef5a5b-f9f8-4ffb-b749-d75055512e94.png)

2022-04-04 19:35 UTC, Janvi-Thakkar commented
@joharikushagra Thanks for the PR! Can you please provide the hover effect on datepicker?

2022-04-05 08:02 UTC, joharikushagra commented
@Janvi-Thakkar could you pls tell what I need to add (border color, focus etc.) on hover?

2022-04-05 20:33 UTC, Janvi-Thakkar commented
> @Janvi-Thakkar could you pls tell what I need to add (border color etc.) on hover?

@joharikushagra You can go wild here but I would suggest changing background color and border.

2022-04-07 05:23 UTC, joharikushagra commented
![Screenshot 2022-04-07 104712](https://user-images.githubusercontent.com/57484457/162126055-12c587d1-c525-4901-9297-b9f04aad898f.png)

2022-04-07 05:24 UTC, joharikushagra commented
@Janvi-Thakkar could you pls confirm

2022-04-07 16:45 UTC, padmajabhol commented
Hi @joharikushagra , is it possible that you remove tailwind from this particular file, so we might not have to do additional changes later? Thanks. If you need help, please let me know.

2022-04-07 17:47 UTC, joharikushagra commented
Hi @padmajabhol, I have used tailwind in datepicker component for applying flex related stuff, styling is default from ant-design

2022-04-07 18:07 UTC, padmajabhol commented
We are trying to do away with tailwind once we have converted everything to ant design.

2022-04-07 18:09 UTC, joharikushagra commented
So should I remove tailwind classes from the component file?

2022-04-07 18:24 UTC, padmajabhol commented
Yes but convert the elements to ant. Please look into the footer component for reference.

2022-04-07 20:49 UTC, joharikushagra commented
![Screenshot 2022-04-08 020702](https://user-images.githubusercontent.com/57484457/162298583-98281937-bec9-47e3-b885-a5cb973be253.png)

@padmajabhol  could you pls confirm the changes?

2022-04-07 21:24 UTC, Janvi-Thakkar commented
> @Janvi-Thakkar could you pls confirm

@joharikushagra The effect looks pretty fine. I have a small suggestion. Instead of showing a cross sign on hover, you can show a normal date picker icon with highlighted color. As it would help to change the date directly if the wrong date is entered.

Please let me know your thought on this :))

2022-04-08 06:11 UTC, joharikushagra commented
@Janvi-Thakkar that cross sign is actually to reset the date, you don't have to click on it, you can simply click on the picker to select the new date in case you have filled the wrong one

2022-04-09 14:45 UTC, Janvi-Thakkar commented
> @Janvi-Thakkar that cross sign is actually to reset the date, you don't need to click on it, you can simply click on the picker to select the new date in case you have filled the wrong one

Okay, Got it :))

2022-04-10 19:44 UTC, joharikushagra commented
@chicken-biryani I guess there's no more change required, could you pls approve the PR

2022-04-10 19:48 UTC, Janvi-Thakkar commented
> @chicken-biryani I guess there's no more change required, could you pls approve the PR


> > @Janvi-Thakkar that cross sign is actually to reset the date, you don't need to click on it, you can simply click on the picker to select the new date in case you have filled the wrong one
> 
> Okay, Got it :))


@joharikushagra can you please run these commands?
git commit --amend --no-edit --signoff
git push --force-with-lease origin master

2022-04-11 08:49 UTC, joharikushagra commented
> > Okay, Got it :))
> 
> @joharikushagra can you please run these commands? git commit --amend --no-edit --signoff git push --force-with-lease origin master

Do I have to run these from my current branch only?

2022-04-11 08:52 UTC, Janvi-Thakkar commented
> > > Okay, Got it :))
> > 
> > 
> > @joharikushagra can you please run these commands? git commit --amend --no-edit --signoff git push --force-with-lease origin master
> 
> Do I have to run these from my current branch only?

@joharikushagra yes, Please replace **master** with your **current-branch-name**

2022-04-11 10:05 UTC, padmajabhol commented
> ![Screenshot 2022-04-08 020702](https://user-images.githubusercontent.com/57484457/162298583-98281937-bec9-47e3-b885-a5cb973be253.png)
> 
> @padmajabhol could you pls confirm the changes?

Looks good!

2022-04-11 18:07 UTC, joharikushagra commented
> git push --force-with-lease origin master

I'm getting this push error on running the second command
![Screenshot 2022-04-11 233158](https://user-images.githubusercontent.com/57484457/162802211-b80cdc4f-9288-4670-b128-1390425f5b48.png)

2022-04-11 18:24 UTC, chicken-biryani approved these changes

2022-04-12 18:23 UTC, sohamsshah requested changes
@joharikushagra LGTM! Thanks for the PR.
Just a small change - Can you please rename the `DatepickerPointAnt.vue` to `DatePickerPoint.vue`?

Other obsolete components can be renamed to `DatePickerOld.vue` (for example). So when we cleanup, we can replace all of them.

2022-04-13 07:25 UTC, joharikushagra commented
> @joharikushagra LGTM! Thanks for the PR. Just a small change - Can you please rename the `DatepickerPointAnt.vue` to `DatePickerPoint.vue`?
> 
> Other obsolete components can be renamed to `DatePickerOld.vue` (for example). So when we cleanup, we can replace all of them.

@sohamsshah renamed the component, pls check

2022-04-19 14:48 UTC, joharikushagra commented
Hi @sohamsshah , could you pls review the changes and merge?

2022-04-30 15:47 UTC, YashKandalkar requested changes
Hey @joharikushagra,
Thanks for working on this PR for so long. I have just left a couple of comments could you please have a look?

Also, since you have renamed some files, can you make sure this does not cause any breaking changes?

2022-04-30 15:47 UTC, YashKandalkar commented on flint.ui/src/components/Datepicker/DatepickerPoint.vue
> -        this.$store.commit('setNew_point_endDate', newValue.split('-').join('/'))
@joharikushagra You seem to have removed the logic for updating the store when a date is selected. Could you please add an explanation to that in the PR comments?

2022-04-30 15:47 UTC, YashKandalkar commented on flint.ui/src/views/flint/ConfigurationsRothC.vue
> +import DatepickerPointAnt from '@/components/Datepicker/DatepickerPointAnt.vue'
Since you have renamed the file to DatepickerPoint, I think you'll need to change the import here as well.

2022-05-05 18:56 UTC, closed without merging