Migrate Vue-2 to Vue-3 for FLINT-UI
moja-global/FLINT-UI pull request #294
Opened 2022-06-02 11:18 UTC by HarshCasper

## Resources

- GitHub: https://github.com/vuejs/core/tree/main/packages/vue-compat
- Blog: https://www.vuemastery.com/blog/vue-3-migration-build/
- Official reference: https://v3-migration.vuejs.org/

2022-06-04 19:32 UTC, Palaksharma23 commented
![image](https://user-images.githubusercontent.com/87171452/172022837-6291d4f0-1df0-46f0-bff1-9249323867dc.png)

Little UI issues are there in GCBM and GCBM is not working fine.

2022-06-05 10:52 UTC, SanjaySinghRajpoot commented
> ![image](https://user-images.githubusercontent.com/87171452/172022837-6291d4f0-1df0-46f0-bff1-9249323867dc.png)
> 
> Little UI issues are there in GCBM and GCBM is not working fine.

Yes, I am having the same issue as above. Moreover, I am unable to see the toggle button below the GCBM heading.  I don't know whether I am only facing this issue or if it's with everyone. Along with I got some warnings with `:v-deep` tag used in the slider component when I first compiled the code. Later they disappeared from the terminal after 2-3 compile reloads

Have a look at this for the above warning https://stackoverflow.com/questions/48032006/how-do-i-use-deep-or-or-v-deep-in-vue-js

Else the changes look to me.

2022-06-05 11:21 UTC, Janvi-Thakkar commented
> > ![image](https://user-images.githubusercontent.com/87171452/172022837-6291d4f0-1df0-46f0-bff1-9249323867dc.png)
> > Little UI issues are there in GCBM and GCBM is not working fine.
> 
> Yes, I am having the same issue as above. Moreover, I am unable to see the toggle button below the GCBM heading. I don't know whether I am only facing this issue or if it's with everyone. Along with I got some warnings with `:v-deep` tag used in the slider component when I first compiled the code. Later they disappeared from the terminal after 2-3 compile reloads
> 
> Have a look at this for the above warning https://stackoverflow.com/questions/48032006/how-do-i-use-deep-or-or-v-deep-in-vue-js
> 
> Else the changes look to me.

I am not even able to see the toggle button neither on the deployed link nor on my local machine.

2022-06-06 04:52 UTC, sohamsshah requested changes
Great work @YashKandalkar ! 👏
Have requested a few minor changes, please incorporate them.

Thanks for the PR!

2022-06-06 04:52 UTC, sohamsshah commented on flint.ui/src/components/FileUpload/FileUpload.vue
> +        :style="{ border: resultDB.isDragActive.value ? '2px dashed #0087ff' : '2px dashed #bdbdbd' }"
Can we replace the inline styling with design system styling or a css class for this case?

2022-06-06 04:52 UTC, sohamsshah commented on flint.ui/src/components/FileUpload/FileUpload.vue
> +          <span>{{ parseFloat((file.size / 1000).toFixed(2)) + ' KB' }}</span>
Abstract this logic into a function in this file or a separate /utils folder

2022-06-06 04:52 UTC, sohamsshah commented on flint.ui/src/components/Stepper/StepperGCBM.vue
> +      if (current == 0) {
Small nitpick:
-  We can use switch-case here
- Add comments for explaining what does `0`, `1` etc. numbers signify

2022-06-06 14:21 UTC, YashKandalkar commented
@Palaksharma23 @Janvi-Thakkar @SanjaySinghRajpoot @sohamsshah Thanks for the review! I have made the requested changes, PTAL

2022-06-06 15:09 UTC, Janvi-Thakkar commented
> @Palaksharma23 @Janvi-Thakkar @SanjaySinghRajpoot @sohamsshah Thanks for the review! I have made the requested changes, PTAL

Great work @YashKandalkar :) The toggle button is still not visible on deployed preview in my machine not sure whether it is only happening with me or if anyone else has the same issue

2022-06-06 16:25 UTC, merged