feat: Changed Stepper, Prompt from Vue 2 to Vue 3
moja-global/FLINT-UI pull request #305
Opened 2022-06-12 04:58 UTC by Palaksharma23

I have changed Stepper, Prompt component from Vue 2 to Vue 3 

@HarshCasper may you please once review this.

2022-06-12 05:17 UTC, HarshCasper approved these changes

2022-06-14 07:46 UTC, YashKandalkar reviewed
Hi - @Palaksharma23 don't we have to provide an `emits` array with all the events that are emitted by a child component in Vue 3?

2022-06-14 07:48 UTC, YashKandalkar requested changes

2022-06-14 07:48 UTC, YashKandalkar commented on flint.ui/src/components/Stepper/StepperPoint.vue
> +  function finalPool() {
The indentation doesn't look right here, can you fix this?

2022-06-17 09:04 UTC, YashKandalkar approved these changes
LGTM :rocket: 
Thanks @Palaksharma23 !

2022-06-17 09:08 UTC, YashKandalkar commented
@Palaksharma23 the build is failing - looks like there are some linting issues, can you have a look?

2022-06-19 13:23 UTC, HarshCasper approved these changes

2022-06-19 13:24 UTC, merged