docs: Added minimum node version to DevelopmentNotes.rst
moja-global/FLINT-UI pull request #410
Opened 2022-09-24 08:25 UTC by abhilipsasahoo03

## Description

This PR fixes #406 

## Change log

- Added minimum node version required to set up the project locally to DevelopmentNotes.rst
- Added installation guide for Node and Yarn to DevelopmentNotes.rst in order to help new contributors get started
- Fixed minor typo

2022-09-24 08:27 UTC, abhilipsasahoo03 commented
@chicken-biryani kindly look into this

2022-09-24 08:28 UTC, chicken-biryani approved these changes

2022-10-10 05:44 UTC, HarshCasper requested changes

2022-10-10 05:44 UTC, HarshCasper commented on docs/DevelopmentGuide/DevelopmentNotes.rst
> +This project requires node version >= 14
`node` -> `Node`

2022-10-10 05:44 UTC, HarshCasper commented on docs/DevelopmentGuide/DevelopmentNotes.rst
> +3. To update node to the latest version, ensure nvm is installed and run the following command:
Link `nvm` here and put it in backticks

2022-10-10 06:48 UTC, abhilipsasahoo03 commented
@HarshCasper please take a look

2022-10-16 10:26 UTC, HarshCasper approved these changes

2022-10-16 10:26 UTC, merged